---
tcb:
  app:
    name: cobranca
  database:
    name: db_tcb_cobranca
    username: ENC(INvBkchPXKUAa6FFg3UXPw==)
    password: ENC(INvBkchPXKUAa6FFg3UXPw==)
    ddlAuto: none
    uri: jdbc:postgresql://localhost
    driver: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
  port: 8084
  profiles:
    active: local
  log:
    level: DEBUG
  i18n:
    enable: false

ws:
  tcb:
    processador: http://localhost:8085/tcbprocessador/api
  google:
    basePath: https://billpaynotification.sandbox.googleapis.com/secure-serving/gsp/
    #basePath: https://billpaynotification.googleapis.com/secure-serving/gsp/

pgp:
  local:
    certificate:
      tcb:
        privateKey: tcb-uat-privatekey.asc
        publicKey: tcb-uat-publickey.asc
      google:
        publicKey: google-uat-publickey.asc
    passwordPrivateKey: totvs@123

jasypt:
  encryptor:
    password: 8fca80be-16ec-47e1-8eb1-678fcc9ed05a
# logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([${tcb.app.name}]){magenta}%clr(%X{contexto}){magenta}%clr(%X{cdTransacao}){magenta} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([${tcb.app.name}]){magenta}%clr(%X{contexto}){magenta}%clr(%X{cdTransacao}){magenta} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    br:
      com:
        totvs:
          tcb: ${tcb.log.level}
    org:
      hibernate:
        type: TRACE
app:
  i18n:
    enable: ${tcb.i18n.enable}
spring:
  ## CONFIGURAÇÃO BANCO DE DADOS
  datasource:
    url: ${tcb.database.uri}/${tcb.database.name}
    username: ${tcb.database.username}
    password: ${tcb.database.password}
    driverClassName: ${tcb.database.driver}
    jndi-name: java:/comp/env/jdbc/tcbDS
  jpa:
    showSql: ${tcb.database.showSql}
    hibernate:
      ddlAuto: ${tcb.database.ddlAuto}
    properties:
      hibernate:
        dialect: ${tcb.database.dialect}
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  profiles:
    active: ${tcb.profiles.active}
server:
  servlet:
    context-path: /tcbcobranca
  port: ${tcb.port}
info:
  build:
    version: ${app.build.version}
trace: true
